Products-Workshop/config/routes.rb
Rails.application.routes.draw do

  resources :products

  root 'products#index'

  Rails.application.routes.draw do
    mount API::Base, at: "/api/"
  end

end

Products-Workshop/app/models/product.rb
class Product < ActiveRecord::Base
  validates_presence_of :name, :short_description, :price, :old_price, :full_description
end

Products-Workshop/app/controllers/api/app_credentials.rb
module API
  class AppCredentials
    APP_KEY = "appkey"
    APP_ID = "railsws"
  end
end

Products-Workshop/app/controllers/api/base.rb
module API
  class Base < Grape::API
    mount API::V1::Base
  end
end

Products-Workshop/app/controllers/api/v1/base.rb
module API
  module V1
    class Base < Grape::API
      mount API::V1::Products
      # mount API::V1::AnotherResource
    end
  end


end

Products-Workshop/app/controllers/api/v1/products.rb
module API
  module V1
    class Products < Grape::API

      helpers do
        def auth
          error!('Unauthorized', 401) unless (headers['App-Key'] == AppCredentials::APP_KEY) && (headers['App-Id'] == AppCredentials::APP_ID)
        end
      end
      before do
          auth
      end

      format :json
      resource :products do
        desc "Return all products"
        get "", root: :products do
          Product.all
        end

        desc "Return a product"
        params do
          requires :id, type: Integer, desc: "ID of the
            product"
        end
        get ":id", root: "product" do
          Product.where(id: params[:id]).first!
        end

        desc "Delete a product"
        params do
          requires :id, type: Integer, desc: "ID of the product"
        end
        delete ":id", root: "product" do
          Product.find(params[:id]).destroy
        end

        desc "Create a new product"
        params do
          requires :name, type: String
          requires :price, type: Integer
          requires :old_price, type: Integer
          requires :short_description, type: String
          requires :full_description, type: String
        end
        post do
          Product.create!({
                              name:params[:name],
                              price:params[:price],
                              old_price:params[:old_price],
                              short_description:params[:short_description],
                              full_description:params[:full_description]
                          })
        end


        desc "Update a product"
        params do
          requires :price, type: Integer
          optional :short_description, type: String
          optional :full_description, type: String
        end
        put ":id" do
          a = Product.find(params[:id])
          a.update!({
                                               price:params[:price],
                                               short_description:params[:short_description],
                                               full_description:params[:full_description]
                                           })
        end
      end
    end
  end
end

Products-Workshop/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Products-Workshop/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path, :notice => "Your product has been saved."
    else
      render "new"
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product), :notice => "Your product has been updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path, :notice => "Your product has been deleted."
  end

  private
    def product_params
      params.require(:product).permit(:name, :price, :old_price, :short_description, :full_description)
    end

    def find_product
      @product = Product.find(params[:id])
    end
end

Products-Workshop/app/helpers/application_helper.rb
module ApplicationHelper
end

Products-Workshop/app/helpers/products_helper.rb
module ProductsHelper
end

Products-Workshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProductsWorkshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p class="notice alert alert-success hide"><%= notice %></p>
    <!-- <p class="alert alert-info"><%= alert %></p> -->


    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand"><%= link_to "ROR WorkShop", root_path %></a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav pull-right">
            <li><%= link_to "add product", new_product_path, class:"" %></li>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <%= yield %>
</body>
</html>

Products-Workshop/app/views/products/_form.html.erb
<%= simple_form_for @product, :html => {:multipart => true, class: "my-form clearfix"} do |f| %>
    <%= f.input :name, label: "Name" %>
    <%= f.input :price %>
    <%= f.input :old_price %>
    <%= f.input :short_description %>
    <%= f.input :full_description %>
    <%= f.button :submit %>
<% end %>

Products-Workshop/app/views/products/edit.html.erb
<section class="section">
    <div class="section__container">
        <h3 class="section__title">Edit Products</h3>
        <%= simple_form_for @product, :html => {:multipart => true, class: 'my-form clearfix'} do |f| %>
            <%= f.input :name, label: "Name" %>
            <%= f.input :price %>
            <%= f.input :old_price %>
            <%= f.input :short_description %>
            <%= f.input :full_description %>
            <%= f.button :submit %>
        <% end %>
    </div>
</section>

Products-Workshop/app/views/products/index.html.erb
<section class="section">
    <div class="section__container">
        <h3 class="section__title">Our Products</h3>
        <table class="table my-table" id="products">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
                    <th>Old Price</th>
                    <th>Short Description</th>
                    <th>Full Description</th>
                    <th class="text-center">Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @products.each do |product| %>
                <tr>
                    <td><%= product.name %></td>
                    <td><%= product.price %></td>
                    <td><%= product.old_price %></td>
                    <td><%= product.short_description %></td>
                    <td><%=product.full_description %></td>
                    <td class="text-center"><%= link_to "Show", product, class:"btn" %>
                        <%= link_to "Edit", edit_product_path(product), class:"btn" %>
                        <%= link_to "Delete", product_path(product), class:"btn", method: :delete, data: {confirm: "Are you sure?"} %> </td>
                </tr>
                <% end %>
            </tbody>
        </table>

    </div>
</section>

Products-Workshop/app/views/products/new.html.erb
<section class="section">
    <div class="section__container">
        <h3 class="section__title">
            New Product
        </h3>
        <%= render 'form' %>
    </div>
</section>

Products-Workshop/app/views/products/show.html.erb
<section class="section">
    <div class="section__container">
        <h3 class="section__title"><%= @product.name %></h3>

        <ul class="list-group">
          <li class="list-group-item clearfix">
            <span class="list-group-title">Product Name:</span>
            <span class="list-group-name"><%= @product.name %></span>
          </li>
          <li class="list-group-item clearfix">
            <span class="list-group-title">Product Price:</span>
            <span class="list-group-name"><%= @product.price %></span>
          </li>
          <li class="list-group-item clearfix">
            <span class="list-group-title">Old Price:</span>
            <span class="list-group-name"><%= @product.old_price %></span>
          </li>
          <li class="list-group-item clearfix">
            <span class="list-group-title">Short Description:</span>
            <span class="list-group-name"><%= @product.short_description %></span>
          </li>
          <li class="list-group-item clearfix">
            <span class="list-group-title">Full Description:</span>
            <span class="list-group-name"><%= @product.full_description %></span>
          </li>
          <li class="list-group-item clearfix">
            <%= link_to "Delete", product_path(@product), class:"btn pull-right", method: :delete, data: {confirm: "Are you sure?"} %>
          </li>
        </ul>

    </div>
</section>